version: "3"

services:
  app:
    build: .
    container_name: flask_app
    depends_on:
      - db
    env_file:
      - ./.flaskenv
    ports:
      - "3000:3000"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data/new_data

volumes:
  postgres-db:
