apiVersion: v1
data:
  DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/flask_db
  FLASK_APP: flask_app.py
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app-flaskenv
  name: flaskenv
